// <auto-generated />
using System;
using EduSphare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduSphare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719112856_AddUserSessions")]
    partial class AddUserSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.AdminProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.InstructorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("HeadLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("InstructorProfiles", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Sessions.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EmailActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Verifications.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("Verifications", (string)null);
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.AdminProfile", b =>
                {
                    b.HasOne("EduSphare.Domain.Users.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("EduSphare.Domain.Users.Profiles.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EduSphare.Domain.Common.ValueObjects.ImageUrl", "ProfileImageUrl", b1 =>
                        {
                            b1.Property<Guid>("AdminProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ProfileImageUrl");

                            b1.HasKey("AdminProfileId");

                            b1.ToTable("AdminProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AdminProfileId");
                        });

                    b.OwnsOne("EduSphare.Domain.Users.Profiles.VO.EmployeeCode", "EmployeeCode", b1 =>
                        {
                            b1.Property<Guid>("AdminProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EmployeeCode");

                            b1.HasKey("AdminProfileId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("AdminProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AdminProfileId");
                        });

                    b.OwnsOne("EduSphare.Domain.Users.Profiles.VO.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("AdminProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("NationalId");

                            b1.HasKey("AdminProfileId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("AdminProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AdminProfileId");
                        });

                    b.Navigation("EmployeeCode")
                        .IsRequired();

                    b.Navigation("NationalId")
                        .IsRequired();

                    b.Navigation("ProfileImageUrl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.InstructorProfile", b =>
                {
                    b.HasOne("EduSphare.Domain.Users.User", "User")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("EduSphare.Domain.Users.Profiles.InstructorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EduSphare.Domain.Common.ValueObjects.ImageUrl", "ProfileImageUrl", b1 =>
                        {
                            b1.Property<Guid>("InstructorProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ProfileImageUrl");

                            b1.HasKey("InstructorProfileId");

                            b1.ToTable("InstructorProfiles");

                            b1.WithOwner()
                                .HasForeignKey("InstructorProfileId");
                        });

                    b.Navigation("ProfileImageUrl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduSphare.Domain.Users.Profiles.StudentProfile", b =>
                {
                    b.HasOne("EduSphare.Domain.Users.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("EduSphare.Domain.Users.Profiles.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EduSphare.Domain.Common.ValueObjects.ImageUrl", "ProfileImageUrl", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ProfileImageUrl");

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.Navigation("ProfileImageUrl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduSphare.Domain.Users.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("InstructorProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
